export { default as App } from './App/App'
export { default as Header } from './Header/Header'
export { default as Footer } from './Footer/Footer'
export { default as HomePage } from './HomePage/HomePage'
export { default as ContactsPage } from './ContactsPage/ContactsPage'
export { default as ServicesPage } from './ServicesPage/ServicesPage'