export const PAGE_HOME_GETDATA_FAILURE = 'PAGE_HOME_GETDATA_FAILURE';
export const PAGE_HOME_GETDATA_REQUEST = 'PAGE_HOME_GETDATA_REQUEST';
export const PAGE_HOME_GETDATA_SUCCESS = 'PAGE_HOME_GETDATA_SUCCESS';
