export const PAGE_SERVICES_GETDATA_FAILURE = 'PAGE_SERVICES_GETDATA_FAILURE';
export const PAGE_SERVICES_GETDATA_REQUEST = 'PAGE_SERVICES_GETDATA_REQUEST';
export const PAGE_SERVICES_GETDATA_SUCCESS = 'PAGE_SERVICES_GETDATA_SUCCESS';
